#!/bin/bash
# compare to number using ifelse statement
echo "Enter the value of a"
read a
echo "Enter the value of b"
read b
if [ $a -gt $b ]
then
        echo " a is equal to b"
else
        echo "a is not equal to b"
fi

